# docker-compose.yml
 
# Reference compose file version 3
version: '3.8'
services:
# Service name is react-app
  react-app:
# build from Dockerfile
    build: .
# we need https. http is 3000
    ports:
    - 3000:3000
    
